export const TOGGLE_DRAWER = 'TOGGLE_DRAWER';
export const TOGGLE_ALERT = 'TOGGLE_ALERT';
export const APP_LOADING = 'APP_LOADING';
export const SET_TOKEN = 'SET_TOKEN';
export const LOADING = 'LOADING';
export const GET_ITEMS = 'GET_ITEMS';
export const SELECT_ITEM = 'SELECT_ITEM';
export const CREATE_ITEM = 'CREATE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const COUNT_CLASSES = 'COUNT_CLASSES';
export const UPDATE_DATA = 'UPDATE_DATA';
export const UPDATE_LOCATION_MAP = 'UPDATE_LOCATION_MAP';
export const EMPTY_ROW_TO_EXPAND = 'EMPTY_ROW_TO_EXPAND';
export const UPDATE_SELECTION='UPDATE_SELECTION' 
export const TOGGLE_ADD_DIALOG='TOGGLE_ADD_DIALOG'
export const DELETE_MULTIPLE='DELETE_MULTIPLE'
export const GLOBAL_URL='http://localhost:8000';

